import type { Metadata } from "next"
import Header from "@/app/_components/Header"
import React, { CSSProperties } from 'react'
import '@/styles/reset.scss'
import styles from '@/styles/styles.module.scss'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface CustomCSSProperties extends CSSProperties {
  '--color-primary'?: string;
  '--color-secondary'?: string;
  '--color-border'?: string;
  '--color-gray'?: string;
}

const colorStyles: CustomCSSProperties = {
  '--color-primary': '#333',
  '--color-secondary': '#06c',
  '--color-border': '#ccc',
  '--color-gray': '#888',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <div style={colorStyles}>
          <Header />
          <div className={styles.content}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
